### ISSUE TITLE
Roadmap to v0.2

### ISSUE THREAD

**Issue by valkyrienyanko** [valkyrienyanko/Unity-ENet-Model#11]
## Packets
* [ ] Server sends position updates of all clients as soon as client joins. This way the client won't have to physically move to reveal themselves.
* [ ] When a client leaves the server, send a message through the server to all the other clients saying that client left the server and remove the GameObject from the scene.
* [ ] Client only sends position updates when they are not moving.
* [ ] Server / Client only send position updates when they are in a specified range of other clients.
* [ ] Show account names hovering above all clients. Send account names to all other clients on join.
* [ ] Allow the client to disconnect from the server by pressing ESC to open up a popup menu to go back to the main menu scene.

## Accounts
* [ ] Add restrictions for account name and password lengths. Add curse filtering.
* [ ] Encrypt password strings sent over the network.
* [ ] Only one client may be logged into one account at a time.
